# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CallYourMom' do
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CallYourMom

  

  platform :ios, '9.0'
  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'react-native-build-config', :path => '../node_modules/react-native-build-config'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'



  target 'CallYourMomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CallYourMom-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CallYourMom-tvOS

  target 'CallYourMom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
